# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the FSOC coarse-alignment tracker (headless build).

The standalone executable is a mandatory graded deliverable, so this file is **source, not build
output**. It is named ``fsoc-tracker.spec`` because ``.gitignore`` ignores ``*.spec`` with an
explicit ``!fsoc-tracker.spec`` negation; any other name silently falls back into the ignore rule
and the spec is one ``git clean`` from being lost.

Two builds from one spec
------------------------
``BUILD_GUI`` selects between them, and they are kept side by side rather than one replacing the
other:

* **headless** (default) -- ``dist/fsoc-tracker``. No Qt at all.
* **GUI** (``BUILD_GUI=1``) -- ``dist/fsoc-tracker-gui``, with PySide6 and pyqtgraph.

Qt platform plugins are a separate class of packaging failure from the base build: they fail at
*runtime*, on the target machine, with an opaque "could not load the Qt platform plugin" rather
than at build time. Keeping the headless executable building and passing its own clean-machine
test means that if Qt packaging fights us we still have a working deliverable, and any failure
that appears is unambiguously a Qt failure rather than a base-packaging one.

There is deliberately **one spec file**, not two: ``.gitignore`` ignores ``*.spec`` with a single
``!fsoc-tracker.spec`` negation, so a second spec file would be silently untracked.

Numba / llvmlite
----------------
``BUNDLE_NUMBA`` controls whether the Numba JIT runtime is included. It is **off by default**,
and that is a measured decision rather than an oversight:

* Nothing in ``src/`` imports ``numba`` or ``llvmlite`` today. The vision pipeline is pure NumPy
  and OpenCV; ``performance.use_numba`` in the config is plumbing for a future hotspot.
* ``libllvmlite.so`` alone is **179 MB**, with the ``numba`` package adding a further 33 MB.
  Bundling them now would roughly triple the executable for code that is never called.

The mechanism is nonetheless implemented and tested, because the point of packaging early is to
prove the path before it is needed. Set ``BUNDLE_NUMBA=1`` in the environment to build with it;
``scripts/build.sh --with-numba`` does exactly that. When a Numba hotspot does land, this flag
flips and nothing else changes.
"""

import os
import sys
from pathlib import Path

from PyInstaller.utils.hooks import (collect_data_files, collect_dynamic_libs,
                                     collect_submodules)

BUNDLE_NUMBA = os.environ.get("BUNDLE_NUMBA", "0") == "1"
BUILD_GUI = os.environ.get("BUILD_GUI", "0") == "1"

binaries = []
hiddenimports = []
datas = []

# --- OpenCV -------------------------------------------------------------------------------
# cv2 ships compiled extension modules and loader shims that PyInstaller's analysis does not
# always follow, so collect them explicitly rather than relying on detection.
binaries += collect_dynamic_libs("cv2")
hiddenimports += ["cv2"]

# --- NumPy --------------------------------------------------------------------------------
# NumPy 2.x moved internals around; collecting the private submodules avoids a frozen-only
# ImportError that does not reproduce from source.
hiddenimports += collect_submodules("numpy._core")
hiddenimports += collect_submodules("numpy.linalg")

# --- Project ------------------------------------------------------------------------------
# Modules reached only through configuration strings are invisible to static analysis.
hiddenimports += collect_submodules("src")

# --- Numba / llvmlite (optional) ------------------------------------------------------------
if BUNDLE_NUMBA:
    # llvmlite's shared library is loaded through ctypes at runtime, so no import graph leads to
    # it and freezing tools do not pick it up. It has to be named explicitly.
    import llvmlite

    binding = Path(llvmlite.__file__).parent / "binding"
    for pattern in ("*.so", "*.dll", "*.dylib"):
        for library in binding.glob(pattern):
            binaries.append((str(library), "llvmlite/binding"))
    hiddenimports += collect_submodules("numba")
    hiddenimports += ["llvmlite", "llvmlite.binding"]

# --- Exclusions -----------------------------------------------------------------------------
# Qt arrives in Phase 7. matplotlib and pytest are development-only: figures are generated by the
# test suite, not by the shipped application.
excludes = ["PyQt5", "PyQt6", "tkinter", "matplotlib", "pytest", "IPython"]
if BUILD_GUI:
    # Qt's platform plugins are loaded by name at runtime, so nothing in the import graph
    # reaches them and PyInstaller's analysis alone is not enough.
    hiddenimports += collect_submodules("pyqtgraph")
    hiddenimports += [
        "PySide6.QtCore", "PySide6.QtGui", "PySide6.QtWidgets", "PySide6.QtOpenGL",
        "shiboken6",
    ]
    binaries += collect_dynamic_libs("PySide6")
    # opencv-python ships its OWN Qt plugins under cv2/qt/plugins. In a GUI build they collide
    # with PySide6's -- PyInstaller fails to extract the duplicate and the application dies at
    # startup with "Failed to extract entry: cv2/qt/plugins/platforms/libqxcb.so", before any
    # window appears. The headless build never hits this because it excludes Qt entirely, which
    # is precisely why the two builds are kept separate: this failure is unambiguously a Qt
    # packaging problem rather than a base one.
    #
    # cv2's Qt plugins exist only to serve cv2.imshow, which this application never calls -- the
    # viewport is a Qt widget. Dropping them is therefore free.
    binaries = [entry for entry in binaries if "cv2/qt" not in entry[0].replace("\\", "/")]
    datas_qt = collect_data_files("PySide6", includes=["Qt/plugins/platforms/*",
                                                       "Qt/plugins/xcbglintegrations/*",
                                                       "Qt/plugins/imageformats/*"])
else:
    excludes += ["PySide6", "shiboken6", "pyqtgraph"]
    datas_qt = []
if not BUNDLE_NUMBA:
    excludes += ["numba", "llvmlite"]

a = Analysis(
    ["src/main.py"],
    pathex=[str(Path(".").resolve())],
    binaries=binaries,
    # The default configuration travels with the executable, so a fresh machine can run it
    # without being handed a config file separately.
    datas=[("config/default.json", "config")] + datas + datas_qt,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
)

if BUILD_GUI:
    # Analysis collects cv2's Qt plugins through its own data hooks as well, so they have to be
    # filtered after analysis, not only from the explicit binaries list above.
    a.binaries = [e for e in a.binaries if "cv2/qt" not in e[0].replace("\\", "/")]
    a.datas = [e for e in a.datas if "cv2/qt" not in e[0].replace("\\", "/")]

# The ONNX candidate discriminator. onnxruntime ships native libraries and the model is a data
# file, so both need collecting explicitly; PyInstaller finds neither by following imports. The
# model is bundled unconditionally rather than behind a flag -- it is 15 KB, and a GUI build that
# silently lacked it would fall back to the classical path with no visible sign.
try:
    binaries += collect_dynamic_libs("onnxruntime")
    datas += collect_data_files("onnxruntime")
    hiddenimports += ["onnxruntime", "onnxruntime.capi", "onnxruntime.capi._pybind_state"]
except Exception:
    pass

_model = os.path.join(os.getcwd(), "models", "discriminator.onnx")
if os.path.exists(_model):
    datas += [(_model, "models")]

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="fsoc-tracker-gui" if BUILD_GUI else "fsoc-tracker",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,          # UPX corrupts some numpy/cv2 shared objects; not worth the size saving.
    # Console stays on even for the GUI build: the demo is judged live, and a Qt plugin failure
    # printing to a console the demonstrator can see is far better than a window that never
    # appears with no explanation anywhere.
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
